    
    <!-- Plugin 1
    <tr>
        <td>
            <center>
                <script type="text/javascript" src="//yandex.st/share/share.js" charset="utf-8"></script>
                <div class="yashare-auto-init b-share_theme_counter" data-yasharel10n="ru" data-yasharequickservices="vkontakte,facebook,twitter,odnoklassniki,moimir" data-yasharetheme="counter" data-yasharelink="http://tushkan.net/news/">
                <span class="b-share-btn__wrap">
                <a rel="nofollow" target="_blank" title="ВКонтакте" class="b-share__handle b-share__link b-share-btn__vkontakte" href="http://share.yandex.ru/go.xml?service=vkontakte&amp;url=http%3A%2F%2Ftushkan.net%2Fnews%2Fsovsem_ne_babnik_2011_smotret_film_onlajn%2F2015-01-21-885&amp;title=%D0%A1%D0%BE%D0%B2%D1%81%D0%B5%D0%BC%20%D0%BD%D0%B5%20%D0%B1%D0%B0%D0%B1%D0%BD%D0%B8%D0%BA%20(2011)%20%D0%A1%D0%BC%D0%BE%D1%82%D1%80%D0%B5%D1%82%D1%8C%20%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%20%D0%BE%D0%BD%D0%BB%D0%B0%D0%B9%D0%BD%20-%2021%20%D0%AF%D0%BD%D0%B2%D0%B0%D1%80%D1%8F%202015" data-service="vkontakte">
                <span class="b-share-icon b-share-icon_vkontakte"></span>
                <span class="b-share-counter">0</span>
                </a>
                </span>
                <span class="b-share-btn__wrap">
                <a rel="nofollow" target="_blank" title="Facebook" class="b-share__handle b-share__link b-share-btn__facebook" href="http://share.yandex.ru/go.xml?service=facebook&amp;url=http%3A%2F%2Ftushkan.net%2Fnews%2Fsovsem_ne_babnik_2011_smotret_film_onlajn%2F2015-01-21-885&amp;title=%D0%A1%D0%BE%D0%B2%D1%81%D0%B5%D0%BC%20%D0%BD%D0%B5%20%D0%B1%D0%B0%D0%B1%D0%BD%D0%B8%D0%BA%20(2011)%20%D0%A1%D0%BC%D0%BE%D1%82%D1%80%D0%B5%D1%82%D1%8C%20%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%20%D0%BE%D0%BD%D0%BB%D0%B0%D0%B9%D0%BD%20-%2021%20%D0%AF%D0%BD%D0%B2%D0%B0%D1%80%D1%8F%202015" data-service="facebook">
                <span class="b-share-icon b-share-icon_facebook"></span>
                <span class="b-share-counter">0</span>
                </a>
                </span>
                <span class="b-share-btn__wrap">
                <a rel="nofollow" target="_blank" title="Twitter" class="b-share__handle b-share__link b-share-btn__twitter" href="http://share.yandex.ru/go.xml?service=twitter&amp;url=http%3A%2F%2Ftushkan.net%2Fnews%2Fsovsem_ne_babnik_2011_smotret_film_onlajn%2F2015-01-21-885&amp;title=%D0%A1%D0%BE%D0%B2%D1%81%D0%B5%D0%BC%20%D0%BD%D0%B5%20%D0%B1%D0%B0%D0%B1%D0%BD%D0%B8%D0%BA%20(2011)%20%D0%A1%D0%BC%D0%BE%D1%82%D1%80%D0%B5%D1%82%D1%8C%20%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%20%D0%BE%D0%BD%D0%BB%D0%B0%D0%B9%D0%BD%20-%2021%20%D0%AF%D0%BD%D0%B2%D0%B0%D1%80%D1%8F%202015" data-service="twitter">
                <span class="b-share-icon b-share-icon_twitter"></span>
                <span class="b-share-counter">0</span>
                </a>
                </span>
                <span class="b-share-btn__wrap">
                <a rel="nofollow" target="_blank" title="Одноклассники" class="b-share__handle b-share__link b-share-btn__odnoklassniki" href="http://share.yandex.ru/go.xml?service=odnoklassniki&amp;url=http%3A%2F%2Ftushkan.net%2Fnews%2Fsovsem_ne_babnik_2011_smotret_film_onlajn%2F2015-01-21-885&amp;title=%D0%A1%D0%BE%D0%B2%D1%81%D0%B5%D0%BC%20%D0%BD%D0%B5%20%D0%B1%D0%B0%D0%B1%D0%BD%D0%B8%D0%BA%20(2011)%20%D0%A1%D0%BC%D0%BE%D1%82%D1%80%D0%B5%D1%82%D1%8C%20%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%20%D0%BE%D0%BD%D0%BB%D0%B0%D0%B9%D0%BD%20-%2021%20%D0%AF%D0%BD%D0%B2%D0%B0%D1%80%D1%8F%202015" data-service="odnoklassniki">
                <span class="b-share-icon b-share-icon_odnoklassniki"></span>
                <span class="b-share-counter">0</span>
                </a>
                </span>
                <span class="b-share-btn__wrap">
                <a rel="nofollow" target="_blank" title="Мой Мир" class="b-share__handle b-share__link b-share-btn__moimir" href="http://share.yandex.ru/go.xml?service=moimir&amp;url=http%3A%2F%2Ftushkan.net%2Fnews%2Fsovsem_ne_babnik_2011_smotret_film_onlajn%2F2015-01-21-885&amp;title=%D0%A1%D0%BE%D0%B2%D1%81%D0%B5%D0%BC%20%D0%BD%D0%B5%20%D0%B1%D0%B0%D0%B1%D0%BD%D0%B8%D0%BA%20(2011)%20%D0%A1%D0%BC%D0%BE%D1%82%D1%80%D0%B5%D1%82%D1%8C%20%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%20%D0%BE%D0%BD%D0%BB%D0%B0%D0%B9%D0%BD%20-%2021%20%D0%AF%D0%BD%D0%B2%D0%B0%D1%80%D1%8F%202015" data-service="moimir">
                <span class="b-share-icon b-share-icon_moimir"></span>
                <span class="b-share-counter"></span>
                </a>
                </span>
                <iframe style="display: none" src="//yastatic.net/share/ya-share-cnt.html?url=http%3A%2F%2Ftushkan.net%2Fnews%2Fsovsem_ne_babnik_2011_smotret_film_onlajn%2F2015-01-21-885&amp;services=vkontakte,facebook,twitter,odnoklassniki,moimir"></iframe>
                </span></div>
            </center>
        </td>
    </tr>
    Plugin 1 -->
    
    <!-- Plugin 2
    <tr>
    <td>
    <center>
    <noindex>
    <div class="share42init"></div>
    <div class="share42init">
    <span id="share42">
    <a rel="nofollow" style="display:inline-block;vertical-align:bottom;width:32px;height:32px;margin:0 6px 6px 0;padding:0;outline:none;background:url(/share42/icons.png) -0px 0 no-repeat" href="#" data-count="vk" onclick="window.open('http://vk.com/share.php?url=http://tushkan.tv/news/<? echo $this->one_news['sbscr'];?>/<? echo date('Y-m-d', $value['addtime']); ?>-<? echo $this->one_news['id'];?>&amp;title=<? echo $this->one_news['title'];?>&amp;image=<? echo $image;?>&amp;description=', '_blank', 'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=550, height=440, toolbar=0, status=0');return false" title="Поделиться В Контакте" target="_blank"></a>
    <a rel="nofollow" style="display:inline-block;vertical-align:bottom;width:32px;height:32px;margin:0 6px 6px 0;padding:0;outline:none;background:url(/share42/icons.png) -32px 0 no-repeat" href="#" data-count="odkl" onclick="window.open('http://www.odnoklassniki.ru/dk?st.cmd=addShare&amp;st._surl=http://tushkan.net/news/<? echo $this->one_news['sbscr'];?>/<? echo date('Y-m-d', $value['addtime']); ?>-<? echo $this->one_news['id'];?>&amp;title=<? echo $this->one_news['title'];?>', '_blank', 'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=550, height=440, toolbar=0, status=0');return false" title="Добавить в Одноклассники" target="_blank"></a>
    <a rel="nofollow" style="display:inline-block;vertical-align:bottom;width:32px;height:32px;margin:0 6px 6px 0;padding:0;outline:none;background:url(/share42/icons.png) -64px 0 no-repeat" href="#" data-count="fb" onclick="window.open('http://www.facebook.com/sharer.php?s=100&amp;p[url]=http://tushkan.net/news/<? echo $this->one_news['sbscr'];?>/<? echo date('Y-m-d', $value['addtime']); ?>-<? echo $this->one_news['id'];?>&amp;p[title]=<? echo $this->one_news['title'];?>&amp;p[summary]=&amp;p[images][0]=', '_blank', 'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=550, height=440, toolbar=0, status=0');return false" title="Поделиться в Facebook" target="_blank"></a>
    <a rel="nofollow" style="display:inline-block;vertical-align:bottom;width:32px;height:32px;margin:0 6px 6px 0;padding:0;outline:none;background:url(/share42/icons.png) -96px 0 no-repeat" href="#" data-count="mail" onclick="window.open('http://connect.mail.ru/share?url=http://tushkan.net/news/<? echo $this->one_news['sbscr'];?>/<? echo date('Y-m-d', $value['addtime']); ?>-<? echo $this->one_news['id'];?>&amp;title=<? echo $this->one_news['title'];?>&amp;description=&amp;imageurl=', '_blank', 'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=550, height=440, toolbar=0, status=0');return false" title="Поделиться в Моем Мире@Mail.Ru" target="_blank"></a>
    <a rel="nofollow" style="display:inline-block;vertical-align:bottom;width:32px;height:32px;margin:0 6px 6px 0;padding:0;outline:none;background:url(/share42/icons.png) -128px 0 no-repeat" href="#" data-count="twi" onclick="window.open('https://twitter.com/intent/tweet?text=<? echo $this->one_news['title'];?>&amp;url=http://tushkan.net/news/<? echo $this->one_news['sbscr'];?>/<? echo date('Y-m-d', $value['addtime']); ?>-<? echo $this->one_news['id'];?>', '_blank', 'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=550, height=440, toolbar=0, status=0');return false" title="Добавить в Twitter" target="_blank"></a>
    <a rel="nofollow" style="display:inline-block;vertical-align:bottom;width:32px;height:32px;margin:0 6px 6px 0;padding:0;outline:none;background:url(/share42/icons.png) -160px 0 no-repeat" href="#" onclick="window.open('https://plus.google.com/share?url=http://tushkan.net/news/<? echo $this->one_news['sbscr'];?>/<? echo date('Y-m-d', $value['addtime']); ?>-<? echo $this->one_news['id'];?>', '_blank', 'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=550, height=500, toolbar=0, status=0');return false" title="Сохранить в Google+" target="_blank"></a>
    <a rel="nofollow" style="display:inline-block;vertical-align:bottom;width:32px;height:32px;margin:0 6px 6px 0;padding:0;outline:none;background:url(/share42/icons.png) -192px 0 no-repeat" href="http://www.livejournal.com/update.bml?event=http://tushkan.net/news/<? echo $this->one_news['sbscr'];?>/<? echo date('Y-m-d', $value['addtime']); ?>-<? echo $this->one_news['id'];?>&amp;subject=<? echo $this->one_news['title'];?>" title="Опубликовать в LiveJournal" target="_blank"></a>
    </span>
    </div>
    </noindex>
    </center>
    </td>
    </tr>
    Plugin 2 -->
    
    <tr>
    <td>
    <center>
    <noindex>
    <script src="/js/social-likes.min.js"></script>
    <link rel="stylesheet" href="/css/social-likes_classic.css">
    <div class="social-image" style="display: none; background: rgb(0, 0, 0);">
        <link rel="image_src" id="image_src" href="<? echo $image; ?>">
    </div>
    <div id="share2" class="social-likes" data-url="<? echo $page_url; ?>" data-image="<? echo $image; ?>" data-title="<? echo $str_title; ?>">
    	<div class="vkontakte" title="Поделиться ссылкой во Вконтакте">Поделиться</div>
        <div class="facebook" title="Поделиться ссылкой на Фейсбуке">Нравится</div>
    	<div class="twitter" title="Поделиться ссылкой в Твиттере">Твитнуть</div>
    	<div class="odnoklassniki" title="Поделиться ссылкой в Одноклассниках">Класс!</div>
        <div class="mailru" title="Поделиться ссылкой в Моём мире">Нравится</div>
    </div>
    <script type="text/javascript">
    /*
    $('#share2').socialLikes({
        url: 'http://github.com/',
        title: 'GitHub',
        data: {
            media: 'http://tushkan.net/admins/uploads/mir_jurskogo_perioda_2015.jpg'  // Image for Pinterest button
        }
    });*/
    </script>
    </noindex>
    </center>
    </td>
    </tr>