<style>.pagination{float: right;}.pagination .active{background: dodgerblue;color: white;}</style>
<script>$(document).ready(function(){$('li .active').removeClass('active');$('#comments').addClass('active');});</script>
<script src="/admins/comments.js"></script>
<script src="/admins/search.js"></script>
<script>$(document).ready(function(){$('.del-search').remove();});</script>
<? echo $this->admintable('Коментарии', 'comments');?>
<ul class="pagination"><?php echo  $this->paginationControl($this->pag,'Sliding','pagination.phtml');  ?></ul>