<link rel="stylesheet" href="/admins/datepicker/css/datepicker.css">
<script src="/admins/datepicker/js/bootstrap-datepicker.js"></script>
<script src="/admins/datepicker/js/service_book_date.js"></script>
<style>.pagination{float: right;}.pagination .active{background: dodgerblue; color: white; }</style>
<script>$(document).ready(function(){$('li .active').removeClass('active');$('#stat').addClass('active');});</script>
<script src="/admins/commstat.js"></script>
<div id="filter_p">
    <? echo $this->admintable($this->title, 'daystat', false);?>
</div>