<style>.pagination{float: right;}.pagination .active{background: dodgerblue; color: white; }</style>
<script>$(document).ready(function(){$('li .active').removeClass('active');$('#news').addClass('active');});</script>
<script src="/admins/news.js"></script>
<script src="/admins/search.js"></script>
<? echo $this->admintable('Новости', 'news');?>
<ul class="pagination"><?php echo  $this->paginationControl($this->pag,'Sliding','pagination.phtml');  ?></ul>