<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <title>Login Admin</title>
    <link href="/admins/login/bootstrap.min.css" rel="stylesheet">
    <link href="/admins/login/login.css" rel="stylesheet">
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="/admins/login/moder.js"></script>
    <script type="text/javascript" src="/admins/login/placeholder.js"></script>
    <script type="text/javascript" src="/admins/login/login.js"></script>

</head>
<body>
<div class="container">

    <form class="form-signin" role="form">

        <h2 style="font-size: 25px;" class="form-signin-heading">Панель управления</h2>
        <input name="ad_username" type="text" class="form-control" placeholder="Логин">
        <input name="ad_password" type="password" class="form-control" placeholder="Пароль">
        <label class="checkbox">
            <input type="checkbox" value="remember-me"> Запомнить меня?
        </label>
        <input class="btn btn-lg btn-primary btn-block" id="admlogin" type="button" value="ВОЙТИ">
        <div style="display:none; margin-top: 5px"  class="alert alert-success"><p>Успешная авторизация</p></div>
    </form>
</div>
</body>
</html>