<?
$title = $this->headTitle("Avatars Menu");
Zend_Registry::set("title",$title);
$meta = $this->headMeta();
Zend_Registry::set("meta",$meta);
?>
<html>
<head>
<style>
a:link {text-decoration:none; color:#4D6D91}
a:visited {text-decoration:none; color:#4D6D91}
a:hover {text-decoration:underline; color:#000000}
td, body {font-family:Tahoma,Arial,Helvetica; font-size:8pt}
input,textarea,select {font-size:10px; font-family:verdana,arial,helvetica}
.menu {padding: 0 0 0 13px; background: url('http://s88.ucoz.net/img/ma/a2.gif') no-repeat 3px 4px;}
</style>
</head>
<body bgcolor="#FFFFFF" topmargin="0" leftmargin="0" rightmargin="0" bottommargin="0" marginwidth="0" marginheight="0" style="padding:5px">
<table border="0" width="100%" cellspacing="1" cellpadding="3">
<tbody>

<tr><td><b>Аватары <span dir="ltr">45x45</span></b></td></tr>
<tr><td><div class="menu"><a href="/index/avatarsavatars/cat/_0" target="avatars">Разное</a></div></td></tr>

<tr><td><b>Аватары <span dir="ltr">64x64</span></b></td></tr>
<tr><td><div class="menu"><a href="/index/avatarsavatars/cat/_1" target="avatars">Мужчины</a></div></td></tr>
<tr><td><div class="menu"><a href="/index/avatarsavatars/cat/_2" target="avatars">Женщины</a></div></td></tr>
<tr><td><div class="menu"><a href="/index/avatarsavatars/cat/_3" target="avatars">Животные</a></div></td></tr>
<tr><td><div class="menu"><a href="/index/avatarsavatars/cat/_4" target="avatars">Кино</a></div></td></tr>
<tr><td><div class="menu"><a href="/index/avatarsavatars/cat/_5" target="avatars">Мультфильмы</a></div></td></tr>
<tr><td><div class="menu"><a href="/index/avatarsavatars/cat/_6" target="avatars">Игры</a></div></td></tr>
<tr><td><div class="menu"><a href="/index/avatarsavatars/cat/_7" target="avatars">Аниме</a></div></td></tr>
<tr><td><div class="menu"><a href="/index/avatarsavatars/cat/_8" target="avatars">Искусство</a></div></td></tr>
<tr><td><div class="menu"><a href="/index/avatarsavatars/cat/_9" target="avatars">Разное</a></div></td></tr>

<tr><td><b>Аватары <span dir="ltr">110x110</span></b></td></tr>
<tr><td><div class="menu"><a href="/index/avatarsavatars/cat/01" target="avatars">Фэнтези</a></div></td></tr>
<tr><td><div class="menu"><a href="/index/avatarsavatars/cat/02" target="avatars">Мужчины</a></div></td></tr>
<tr><td><div class="menu"><a href="/index/avatarsavatars/cat/03" target="avatars">Женщины</a></div></td></tr>
<tr><td><div class="menu"><a href="/index/avatarsavatars/cat/04" target="avatars">Животные</a></div></td></tr>
<tr><td><div class="menu"><a href="/index/avatarsavatars/cat/05" target="avatars">Игры</a></div></td></tr>
<tr><td><div class="menu"><a href="/index/avatarsavatars/cat/06" target="avatars">Кино</a></div></td></tr>
<tr><td><div class="menu"><a href="/index/avatarsavatars/cat/07" target="avatars">Мультфильмы</a></div></td></tr>
<tr><td><div class="menu"><a href="/index/avatarsavatars/cat/08" target="avatars">Аниме</a></div></td></tr>
<tr><td><div class="menu"><a href="/index/avatarsavatars/cat/09" target="avatars">Цветы</a></div></td></tr>
<tr><td><div class="menu"><a href="/index/avatarsavatars/cat/10" target="avatars">Знаменитости</a></div></td></tr>
<tr><td><div class="menu"><a href="/index/avatarsavatars/cat/11" target="avatars">Вещи</a></div></td></tr>
<tr><td><div class="menu"><a href="/index/avatarsavatars/cat/12" target="avatars">Части тела</a></div></td></tr>
<tr><td><div class="menu"><a href="/index/avatarsavatars/cat/13" target="avatars">Искусство</a></div></td></tr>
<tr><td><div class="menu"><a href="/index/avatarsavatars/cat/14" target="avatars">Разное</a></div></td></tr>
<tr><td><div class="menu"><a href="/index/avatarsavatars/cat/15" target="avatars">Дети</a></div></td></tr>

</tbody>
</table>


</body></html>