<?
$memcache = Zend_Registry::get("memcache");
$user = (array) Model_User::getUserById($this->user_id);
$title = $this->headTitle("Материалы пользователя [".$user['username']."] - Смотреть онлайн фильмы бесплатно и без регистрации");
Zend_Registry::set("title",$title);
$meta = $this->headMeta();
Zend_Registry::set("meta",$meta);
$user_online = Zend_Registry::get("user");
?>
<script>
    $(document).ready(function(){
        $("#breadcrumbs").append('<a href="/">Главная</a> » <b style="font-weight:normal;">Материалы пользователя [<? echo $user['username']." (<b>".$this->count_news."</b>)"; ?>]</b>');
    });
</script>
<table border="0" cellpadding="0" cellspacing="0" width="100%">
    <tbody><tr>
        <td align="right">
            <?php echo $this->paginationControl($this->news, 'Sliding',
                'partials/paginator_user_news.phtml'); ?>
        </td>
    </tr>
    </tbody>
</table>
<script type="text/javascript">function ban_item(id){if (confirm('Вы действительно хотите активировать данный материал?')){var img=document.getElementById('bi'+id);img.src='http://s88.ucoz.net/img/fr/EmnAjax.gif';_uPostForm('',{url:'http'+'://tushkan.net/index/86-'+id+'-1'});}}function del_item(id){if (confirm('Вы подтверждаете удаление?')){var img=document.getElementById('di'+id);img.src='http://s88.ucoz.net/img/fr/EmnAjax.gif';_uPostForm('',{url:'http'+'://tushkan.net/index/',type:'POST',data:{ssid:'GbwGF8ow',a:'38',s:id}});}}</script>
<div id="allEntries">
    <? $user_online = Zend_Registry::get("user"); ?>
    <? foreach ($this->news as $value){

        $key = md5($value['tags']);
        if(($tags = $memcache->get($key)) === false) {
            $tags = Model_News::getNewsTagsInfo($value['tags']);
            $memcache->set($key, $tags, false, 3600 * 24 * 7);
        }

        if( ($value['hide_on_site'] == 0) ||
            ($value['hide_on_site'] == 1 && 
              ($user_online->data['group_id'] == "5" || $user_online->data['group_id'] == "8" || $user_online->data['group_id'] == "9")
            )
        ){ ?>
        <div id="entryID_<? echo $value['id']; ?>">
            <table style="width: 100%; border-collapse: collapse" border="0">
                <tbody>
                <tr>
                    <td style="width: 41px; height: 32px; letter-spacing: 0px; word-spacing: 0px; background-image: url(/tmpl_winskin/news/ico.png); background-repeat: no-repeat; background-position: 50% 50%" rowspan="1"><br>
                    </td>
                    <td style="padding-left: 5px; letter-spacing: 0px; word-spacing: 0px" align="left">
                        <div class="news_title">
                            <h3 title="<? echo $value['title']; ?>"><font face="Arial"><a href="/news/<? echo $value['sbscr']; ?>/<? echo date('Y-m-d', $value['urltime']); ?>-<? echo $value['id']; ?>"><? echo $this->cutTitle($value['title']); ?></a></font></h3></div>
                    </td>
                </tr>
                </tbody>
            </table>
            <table style="width: 100%; border-collapse: collapse;" border="0">
                <tbody>
                <tr>
                    <td style="letter-spacing: 0px; word-spacing: 0px; width: 150px; text-align: center; vertical-align: middle" rowspan="1" align="center">
                        <a href="/news/<? echo $value['sbscr']; ?>/<? echo date('Y-m-d', $value['urltime']); ?>-<? echo $value['id']; ?>" title="<? echo $this->cutTitle($value['title']); ?>" class="highslide" onclick="return hs.expand(this, {captionId: 'caption1'})">
                            <img style="border:2px solid #d5d5d5;-moz-border-radius:4px;border-radius:4px;" width="150" height="210" align="left" vspace="5" hspace="5" alt="" src="<? echo $value['other1']; ?>"></a>
                    </td>
                    <td style="vertical-align: top; letter-spacing: 0px; word-spacing: 0px; padding-left: 5px; padding-top: 3px; text-align: justify">

                 <span class="short_descr item_player" style="font-size:12pt; font-family: Calibri, Arial, Helvetica, sans-serif; color:#020204; line-height: 1.2;">
                 <? $item_message = str_replace("\\", "", $value['message']);
                    $pos_1 = strpos($item_message,"\$CUT$");
                    $str_2 = substr($item_message,0,$pos_1);
                    $item_message = str_replace(array("<hr>", '<hr />', '<hr size="2" width="100%">'), "", $str_2);
                    $item_message = $this->showFilmTags($tags, $item_message);
                    echo "<hr>".$item_message;
                 ?>
                     <span class="entDots">... </span>
                     <span class="entryReadAll"><a class="entryReadAllLink" href="/news/<? echo $value['sbscr']; ?>/<? echo date('Y-m-d', $value['urltime']); ?>-<? echo $value['id']; ?>">.</a>
                     </span>
                 </span> <br><br></td></tr></tbody></table>
            <table style="height: 23px; width: 650px; border-collapse: collapse" border="0"><tbody>
                <tr style="background-image: url(&quot;/lis/ramka_ny.png&quot;); height: 23px; width: 650px; background-repeat: no-repeat; background-position: 50% 100%;">

                    <td width="80%" style="clear:none !important; height: 23px; letter-spacing: 0px; word-spacing: 0px; padding-left: 3px; padding-top: 0px;" align="left">
                        <div class="news_descr" style="clear:right;">
                            <? echo $value['cat_name']; ?>
                            <? if($user_online->data['is_registered']){echo "| Просмотров: ".$value['reads1']; } ?>
                            | Комментарии (<? echo $value['num_com'] ? $value['num_com'] : '0'; ?>) | Добавлен: <?
                            $date_now = time();
                            $date_time_array = getdate($date_now);
                            $month = $date_time_array['mon'];
                            $day = $date_time_array['mday'];
                            $year = $date_time_array['year'];
                            $date_time_array = getdate($value['addtime']);
                            $month_2 = $date_time_array['mon'];
                            $day_2 = $date_time_array['mday'];
                            $year_2 = $date_time_array['year'];
                            $date_1 = mktime(0,0,0,$month,$day,$year);
                            $date_2 = mktime(0,0,0,$month_2,$day_2,$year_2);
                            $date_3 = mktime(0,0,0,$month,$day-1,$year);
                            if($date_1 == $date_2){
                                echo "Сегодня ".date('H:i', $value['addtime']);
                            }elseif($date_2 == $date_3){
                                echo "Вчера ".date('H:i', $value['addtime']);
                            }else{
                                echo date('d.m.Y H:i', $value['addtime']);
                            }
                            ?>
                        </div></td>
                    <? if($user_online->data['group_id'] == "5" || $user_online->data['group_id'] == "8" || $user_online->data['group_id'] == "9" || ($user_online->data['group_id'] != "11" && $user_online->data['user_id'] == $value['other6']) ){ echo '<td><a href="/tncontrol/editnews/id/'.$value['id'].'" style="color:red;float:right;" title="Редактировать"><img src="/img/edit_icon.png" alt=""/></a></td>'; }?>
                    <td width="17%" style="padding-right: 2px;" align="right">
                        <div class="photo_block">

                            <a href="#" title="Минуснуть" onclick="uplusminusrating(2,<? echo $value['id']; ?>,1);return false">
                                <div class="photo_m"></div></a>


                            <a href="#" title="Плюсануть" onclick="uplusminusrating(2,<? echo $value['id']; ?>,4);return false">
                                <div class="photo_p"></div></a>


                            <div class="photo_plus">

                <span title="Голосов: <? $tmp_1 = round($value['rating']*$value['rate_num']);
                   $tmp_2 = 2*$value['rate_num'];
                   $tmp_3 = $tmp_1 - $tmp_2;
                   echo $tmp_3; ?>" id="rate_<? echo $value['id']; ?>"><? echo $tmp_3; ?></span>
                            </div>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    <? } ?>
    <? } ?>
</div>
<div class="catPages2" align="center" style="clear:both;" id="pagesBlock2"> 
<?php echo $this->paginationControl($this->news, 'Sliding',
                'partials/paginator_user_news_2.phtml'); ?>
</div>