<?
$title = $this->headTitle("Ошибка 404");
Zend_Registry::set("title",$title);
$meta = $this->headMeta();
Zend_Registry::set("meta",$meta);
?>
<!--<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>.breadcrumbs{display: none;}</style>
</head>
<body>-->
<div class="container" style="width: 656px; margin: 0 auto;">
  <h1 style="font-size: 40px; font-weight: bold;text-align: center;">Ошибка 404</h1>
  <h2 style="text-align: center;"><?php echo $this->message ?></h2>

  <?php if (isset($this->exception)): ?>
  
  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
  </pre>

  <?php endif ?>
</div>
<!--</body>
</html>-->