<?php
$memcache = Zend_Registry::get("memcache");
/*$key = 'news_blocks_publ_index';
if(($result = $memcache->get($key)) === false ) {
    $news_blocks_res = Model_News::getNewsBlocksById(27);
    $memcache->set($key, $news_blocks_res, false, 3600);
} else {
    $news_blocks_res = $result;
}
if ($news_blocks_res){$news_blocks = (array)$news_blocks_res;}*/
global $news_blocks; $news_blocks = getSeoInfo();
if($this->page_number > 0){
    $title_str = $news_blocks['title_main']." (".$this->page_number." страница)";
}else{
    $title_str = $news_blocks['title_main'];
}
$this->headTitle($title_str);

$key = 'meta_publ_pages';
if(($result = $memcache->get($key)) === false ) {
    $meta_arr = Model_MetaTags::getMetaTagsByLocation("publ_pages");
    $memcache->set($key, $meta_arr, false, 3600);
} else {
    $meta_arr = $result;
}
$meta = "";
foreach($meta_arr as $item){
    $meta .= '<meta name="'.$item['name'].'" content="'.$item['content'].'" />
';
}
$meta .= $this->headMeta();
Zend_Registry::set("meta",$meta);

if($news_blocks){
?><center style="margin-top: -20px;">
<? echo $news_blocks['title_up']?>
</center>
<hr>
<?}?>
<table border="0" cellpadding="0" cellspacing="0" width="100%">
    <tbody><tr>
        <td align="right"><?php echo $this->paginationControl($this->publs, 'Sliding',
                'partials/paginator_publ_main.phtml'); ?></td>
    </tr>
    </tbody>
</table>
<? $user_online = Zend_Registry::get("user"); ?>
<div id="allEntries">
<? foreach ($this->publs as $key=>$value){ 
    if( ($value['hide_on_site'] == 0) || 
            ($value['hide_on_site'] == 1 && 
              ($user_online->data['group_id'] == "5" || $user_online->data['group_id'] == "8" || $user_online->data['group_id'] == "9")
            )
        ){
?>
<div id="entryID_<? echo $value['id']; ?>">
    <table style="width: 100%; border-collapse: collapse" cellspacing="1" cellpadding="1">
        <tbody>
        <tr>
            <td style="padding-left: 5px; letter-spacing: 0px; word-spacing: 0px" align="left">
                <div class="news_title">
                <a href="/publ/<?if($value['cat_pass'] != ""){ echo $value['cat_pass']."/";}?><? echo $value['url'].'/'.$value['catID'].'-1-0-'.$value['id']; ?>">
                <font face="Arial"><h3><? echo $value['title']; ?></h3></font></a></div>
            </td>
        </tr>
        </tbody>
    </table>

    <table style="width: 100%; border-collapse: collapse" cellspacing="1" cellpadding="1">
        <tbody>
        <tr><td></td></tr>
        <tr>
            <td>
                <? if($value['asite'] != "") {?>
                <hr>
                <div align="center">
                    <a href="/publ/<?if($value['cat_pass'] != ""){ echo $value['cat_pass']."/";}echo $value['url'].'/'.$value['catID'].'-1-0-'.$value['id']; ?>" alt="<? echo str_replace('"', "'", $value['title']); ?>" title="<? echo str_replace('"', "'", $value['title']); ?>" class="highslide" onclick="return hs.expand(this, {captionId: 'caption1'})">
                    <img width="300" border="1" align="center" vspace="4" hspace="10" src="<? echo $value['asite']; ?>"></a>
                </div>
                <? } ?>
            </td>
        </tr>
        <tr>
            <td style="vertical-align: top; letter-spacing: 0px; word-spacing: 0px; padding-left: 5px; padding-top: 3px; text-align: justify">

                <span style="font-size:12pt; font-family: Calibri, Arial, Helvetica, sans-serif; color:#2e2e2e">
                    <?
                    $item_message = str_replace("\\", "", $value['brief']);
                    echo $item_message;
                    ?>
                </span> <br><br>
            </td>
        </tr>
        </tbody>
    </table>
    <table style="width: 100%; border-collapse: collapse" border="0">
        <tbody>
        <tr style="background-color: #D7DCE2; border: 1px solid #82A2BB;  background-repeat: no-repeat; background-position: 50% 100%;">

            <td width="90%" style="clear:none !important; height: 23px; letter-spacing: 0px; word-spacing: 0px; padding-left: 3px; padding-top: 3px;" align="left">
                <div class="news_descr" style="clear:right;">
                    <!--<a href="/publ/<? //if($value['cat_pass'] != ""){ echo $value['cat_pass']."/";} echo $value['catID'];?>">-->
                    <? echo $value['cat_name'];?>
                    <!--</a>-->
                    <? if($user_online->data['is_registered']){echo "| Просмотров: ".$value['reads1']; } ?>
                    | Комментарии (<!--<a href="/publ/<?if($value['cat_pass'] != ""){ echo $value['cat_pass']."/";}?><? echo $value['url']; ?>/<? echo $value['catID']; ?>-1-0-<? echo $value['id']; ?>#comments">--><? if($value['num_com'] > 0){ echo $value['num_com']; }else{ echo "0"; } ?><!--</a>-->) | Добавлен: <?
                            $date_now = time();
                            $date_time_array = getdate($date_now);
                            $month = $date_time_array['mon'];
                            $day = $date_time_array['mday'];
                            $year = $date_time_array['year'];
                            $date_time_array = getdate($value['addtime']);
                            $month_2 = $date_time_array['mon'];
                            $day_2 = $date_time_array['mday'];
                            $year_2 = $date_time_array['year'];
                            $date_1 = mktime(0,0,0,$month,$day,$year);
                            $date_2 = mktime(0,0,0,$month_2,$day_2,$year_2);
                            $date_3 = mktime(0,0,0,$month,$day-1,$year);
                            if($date_1 == $date_2){
                                echo "Сегодня ".date('H:i', $value['addtime']);
                            }elseif($date_2 == $date_3){
                                echo "Вчера ".date('H:i', $value['addtime']);
                            }else{
                                echo date('d.m.Y, H:i', $value['addtime']);
                            }
                            ?>
                </div>
            </td>
            <? if($user_online->data['group_id'] == "5" || $user_online->data['group_id'] == "8" || $user_online->data['group_id'] == "9"){ echo '<td><a href="/tncontrol/editpubl/id/'.$value['id'].'" style="color:red;float:right;" title="Редактировать"><span class="edit_item_film_img"></span></a></td>'; }?>
            <!--<td width="17%" style="clear:none !important; height: 23px;">
                <div class="dalee">
                    <a class="dalee" href="/publ/<? /*if($value['cat_pass'] != ""){ echo $value['cat_pass']."/";}?><? echo $value['url']; ?>/<? echo $value['catID']; ?>-1-0-<? echo $value['id']; */?>">Подробнее</a>
                </div>
            </td>-->

        </tr>
        </tbody>
    </table><br>
</div>
<? } ?>
<? } ?>
</div>
<div style="text-align:center;">
    <?php echo $this->paginationControl($this->publs, 'Sliding',
                'partials/paginator_publ_main_2.phtml'); ?>
</div>

<? /*<div class="cattext"> if($news_blocks){ echo $news_blocks['title_down']; } </div> */?>