<? $user_id = Zend_Controller_Front::getInstance()->getRequest()->getParam("id");
$server_uri = $_SERVER["REQUEST_URI"];
$page_number = 1;
$min_pos_1 = strpos($server_uri, "-");
$str1 = substr($server_uri,$min_pos_1+1);
$min_pos_2 = strpos($str1, "-");
$str2 = substr($str1,$min_pos_2+1);
$min_pos_3 = strpos($str2, "-");
$str_pn = substr($str2,0,$min_pos_3);
$page_number = (int)($str_pn);

$str3 = substr($str2,$min_pos_3+1);
$min_pos_4 = strpos($str3, "-");
$str4 = substr($str3,$min_pos_4+1);
$min_pos_5 = strpos($str4, "-");
$str_uid = substr($str4,$min_pos_5+1);
$user_id = (int)($str_uid);
?>
<?php if ($this->pageCount): ?>
    <span class="pagesBlockuz1">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
    <a class="swchItem" href="<?php echo "/news/0-0-".$this->previous."-0-17-".$user_id; ?>">
        <span>«</span>
    </a>
<?php else: ?>
    <span class="disabled" style="display: none;">«</span>
<?php endif; ?>

<?php if (isset($this->previous)): ?>
        <? if(($this->current) < 6 ){?>
        <? } else {?>
            <a class="swchItem" href="<?php echo "/news/0-0-".$this->first."-0-17-".$user_id; ?>">
        <span><?php echo $this->first; ?></span>
    </a>
    
    <a class="swchItem" href="<?php echo "/news/0-0-".($this->first+1)."-0-17-".$user_id; ?>">
        <span><?php echo ($this->first+1); ?></span>
    </a>
            ...
        <?} ?>
    <? endif;?>
    
<?php if (isset($this->next)): ?>
        <? if(($this->current) == 5 ){?>
            <a class="swchItem" href="<?php echo "/news/0-0-".$this->first."-0-17-".$user_id; ?>">
        <span><?php echo $this->first; ?></span>
    </a>
    
    <a class="swchItem" href="<?php echo "/news/0-0-".($this->first+1)."-0-17-".$user_id?>">
        <span><?php echo ($this->first+1); ?></span>
    </a>
        <?} ?>
    <? endif;?>
    
<?php if (isset($this->next)): ?>
        <? if(($this->current) == 4 ){?>
            <a class="swchItem" href="<?php echo "/news/0-0-".$this->first."-0-17-".$user_id; ?>">
        <span><?php echo $this->first; ?></span>
    </a>
        <?} ?>
    <? endif;?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
    <?php if ($page != $this->current): ?>
        <a class="swchItem" href="<?php echo "/news/0-0-".$page."-0-17-".$user_id; ?>">
            <span><?php echo $page; ?></span>
        </a>
    <?php else: ?>
        <b class="swchItemA"><span><?php echo $page; ?></span></b>
    <?php endif; ?>
<?php endforeach; ?>

<?php if (isset($this->next)): ?>
        <? if(($this->current) > ($this->pageCount - 5) ){?>
        <? } else {?>
            ...
            <a class="swchItem" href="<?php echo "/news/0-0-".($this->last-1)."-0-17-".$user_id; ?>">
        <span><?php echo ($this->last-1); ?></span>
    </a>
    
    <a class="swchItem" href="<?php echo "/news/0-0-".$this->last."-0-17-".$user_id; ?>">
        <span><?php echo $this->last; ?></span>
    </a>
        <?} ?>
    <? endif;?>
    
<?php if (isset($this->next)): ?>
        <? if(($this->current) == ($this->pageCount - 3) ){?>
    
    <a class="swchItem" href="<?php echo "/news/0-0-".$this->last."-0-17-".$user_id; ?>">
        <span><?php echo $this->last; ?></span>
    </a>
        <?} ?>
    <? endif;?>
    
<?php if (isset($this->next)): ?>
        <? if(($this->current) == ($this->pageCount - 4) ){?>
            <a class="swchItem" href="<?php echo "/news/0-0-".($this->last-1)."-0-17-".$user_id; ?>">
        <span><?php echo ($this->last-1); ?></span>
    </a>
    
    <a class="swchItem" href="<?php echo "/news/0-0-".$this->last."-0-17-".$user_id; ?>">
        <span><?php echo $this->last; ?></span>
    </a>
        <?} ?>
    <? endif;?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
    <a class="swchItem" href="<?php echo "/news/0-0-".$this->next."-0-17-".$user_id; ?>">
        <span>»</span>
    </a>
<?php else: ?>
    <span class="disabled" style="display: none;">»</span>
<?php endif; ?>
</span>
<?php endif; ?>
