<?php
$server_uri = $this->url();
$str = substr($server_uri,1); // убираем первый слеш "/"
$is_news = strpos($str, "news");
$page_number = 0;
$category_name = "";
if($is_news === false){
    var_dump("error url");die;
}else{
    $str = substr($str,5); // убираем строку "news"
    $is_slash = strpos($str, "/");
    if($is_slash === false){ // если нету в строке "/"
        $min_pos_1 = strpos($str, "-");
        if($min_pos_1 === false){
            $page_number = (int)($str);
        }else{
            $str2 = substr($str,0,$min_pos_1);
            $page_number = (int)($str2);
            $str3 = substr($str,$min_pos_1+1);
            $min_pos_2 = strpos($str3, "-");
            $str4 = substr($str3,0,$min_pos_2);
            $second_param = (int)($str4);
            $str5 = substr($str3,$min_pos_2+1);
            $category_id = (int)($str5);
        }
    }else{
        $category_name = substr($str,0,$is_slash);
        $str2 = substr($str,$is_slash+1);
        $min_pos_1 = strpos($str2, "-");
        if($min_pos_1 === false){
            $page_number = (int)($str2);
        }else{
            $str3 = substr($str2,0,$min_pos_1);
            $page_number = (int)($str3);
            $str4 = substr($str2,$min_pos_1+1);
            $min_pos_2 = strpos($str4, "-");
            $str5 = substr($str4,0,$min_pos_2);
            $second_param = (int)($str5);
            $str6 = substr($str4,$min_pos_2+1);
            $category_id = (int)($str6);
        }
    }

}

?>
<? $item_per_page = MOVIE_ON_PAGE; // количество итемов на странице ?>
<?php if ($this->pageCount): ?>
<span class="pagesBlockuz1">

<?php if (isset($this->previous)): ?>
        <? if(($this->current) < 6 ){?>
        <? } else {?>
            <a class="swchItem" href="<?php if($category_name != ""){ echo "/news/".$category_name."/".$this->first."-0-".$category_id; }
    else{ echo "/news/".$this->first."-0-".$category_id; }
    ?>">
        <span><?php echo $this->first."-".($item_per_page); ?></span>
    </a>
    
    <a class="swchItem" href="<?php if($category_name != ""){ echo "/news/".$category_name."/".($this->first+1)."-0-".$category_id; }
    else{ echo "/news/".($this->first+1)."-0-".$category_id; }
    ?>">
        <span><?php echo (($item_per_page * $this->first)+1)."-".($item_per_page * ($this->first+1)); ?></span>
    </a>
            ...
        <?} ?>
    <? endif;?>
    
<?php if (isset($this->next)): ?>
        <? if(($this->current) == 5 ){?>
            <a class="swchItem" href="<?php if($category_name != ""){ echo "/news/".$category_name."/".$this->first."-0-".$category_id; }
    else{ echo "/news/".$this->first."-0-".$category_id; }
    ?>">
        <span><?php echo $this->first."-".($item_per_page); ?></span>
    </a>
    
    <a class="swchItem" href="<?php if($category_name != ""){ echo "/news/".$category_name."/".($this->first+1)."-0-".$category_id; }
    else{ echo "/news/".($this->first+1)."-0-".$category_id; }
    ?>">
        <span><?php echo (($item_per_page * $this->first)+1)."-".($item_per_page * ($this->first+1)); ?></span>
    </a>
        <?} ?>
    <? endif;?>
    
<?php if (isset($this->next)): ?>
        <? if(($this->current) == 4 ){?>
            <a class="swchItem" href="<?php if($category_name != ""){ echo "/news/".$category_name."/".$this->first."-0-".$category_id; }
    else{ echo "/news/".$this->first."-0-".$category_id; }
    ?>">
        <span><?php echo $this->first."-".($item_per_page); ?></span>
    </a>
        <?} ?>
    <? endif;?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a class="swchItem" href="<?php if($category_name != ""){ echo "/news/".$category_name."/".$page."-0-".$category_id; }
    else{ echo "/news/".$page."-0-".$category_id; }
    ?>">
        <span><?php if($page == 1 && $this->totalItemCount < $item_per_page){echo $page."-".($this->totalItemCount);}elseif($page == 1 && $this->totalItemCount >= $item_per_page){echo $page."-".($item_per_page);}elseif($page == $this->last){ echo ((($item_per_page) * ($page - 1))+1)."-".($this->totalItemCount); }else{ echo ((($item_per_page) * ($page - 1))+1)."-".(($item_per_page) * ($page)); } ?></span>
    </a>
  <?php else: ?>
        <b class="swchItemA"><span><?php if($page == 1 && $this->totalItemCount < $item_per_page){echo $page."-".($this->totalItemCount);}elseif($page == 1 && $this->totalItemCount >= $item_per_page){echo $page."-".($item_per_page);}elseif($page == $this->last){ echo ((($item_per_page) * ($page - 1))+1)."-".($this->totalItemCount); }else{ echo ((($item_per_page) * ($page - 1))+1)."-".(($item_per_page) * ($page)); } ?></span></b>
  <?php endif; ?>
<?php endforeach; ?>

<?php if (isset($this->next)): ?>
        <? if(($this->current) > ($this->pageCount - 5) ){?>
        <? } else {?>
            ...
            <a class="swchItem" href="<?php if($category_name != ""){ echo "/news/".$category_name."/".($this->last-1)."-0-".$category_id; }
    else{ echo "/news/".($this->last-1)."-0-".$category_id; }
    ?>">
        <span><?php echo (($item_per_page * (($this->last)-2))+1)."-".($item_per_page * (($this->last)-1)); ?></span>
    </a>
    
    <a class="swchItem" href="<?php if($category_name != ""){ echo "/news/".$category_name."/".$this->last."-0-".$category_id; }
    else{ echo "/news/".$this->last."-0-".$category_id; }
    ?>">
        <span><?php echo (($item_per_page * (($this->last)-1))+1)."-".($this->totalItemCount); ?></span>
    </a>
        <?} ?>
    <? endif;?>
    
<?php if (isset($this->next)): ?>
        <? if(($this->current) == ($this->pageCount - 3) ){?>
    
    <a class="swchItem" href="<?php if($category_name != ""){ echo "/news/".$category_name."/".$this->last."-0-".$category_id; }
    else{ echo "/news/".$this->last."-0-".$category_id; }
    ?>">
        <span><?php echo (($item_per_page * (($this->last)-1))+1)."-".($this->totalItemCount); ?></span>
    </a>
        <?} ?>
    <? endif;?>
    
<?php if (isset($this->next)): ?>
        <? if(($this->current) == ($this->pageCount - 4) ){?>
            <a class="swchItem" href="<?php if($category_name != ""){ echo "/news/".$category_name."/".($this->last-1)."-0-".$category_id; }
    else{ echo "/news/".($this->last-1)."-0-".$category_id; }
    ?>">
        <span><?php echo (($item_per_page * (($this->last)-2))+1)."-".($item_per_page * (($this->last)-1)); ?></span>
    </a>
    
    <a class="swchItem" href="<?php if($category_name != ""){ echo "/news/".$category_name."/".$this->last."-0-".$category_id; }
    else{ echo "/news/".$this->last."-0-".$category_id; }
    ?>">
        <span><?php echo (($item_per_page * (($this->last)-1))+1)."-".($this->totalItemCount); ?></span>
    </a>
        <?} ?>
    <? endif;?>

</span>
<?php endif; ?>
